import * as THREE from 'three';
import {VRButton} from 'three/addons/webxr/VRButton.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);$('room').value=params.get('room')||'TOKYO';
let ws,role,state,joined=false,selected='tank',yaw=0,pitch=-.25,renderer,scene,camera,rig,vrButton,paused=false;
const keys={},objects=new Map(),unitObjects=new Map(),effectObjects=new Map();let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',2800);}
function send(data){if(ws?.readyState===1)ws.send(JSON.stringify(data));}
for(const b of document.querySelectorAll('[data-role]'))b.onclick=()=>join(b.dataset.role);
function join(r){role=r;ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}`);$('connection').textContent='CONNECTING';ws.onopen=()=>send({type:'join',room:$('room').value.trim().toUpperCase(),role});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.error){toast(m.error);return;}if(m.joined){joined=true;$('lobby').hidden=true;$('game').hidden=false;$('connection').textContent=`${m.room} / ${role.toUpperCase()}`;setup();}if(m.state){state=m.state;paused=m.paused;updateUI(m.players);if(role==='defender')drawMap();}};ws.onclose=()=>{joined=false;$('connection').textContent='DISCONNECTED — RELOAD TO REJOIN';toast('Connection lost. Reload and join the same room.');};ws.onerror=()=>toast('Could not connect to game server');}
$('start').onclick=()=>send({type:'start'});$('practice').onclick=()=>send({type:'start',practice:true});$('reset').onclick=()=>send({type:'reset'});
function setup(){
 $('controls').replaceChildren();const items=role==='kaiju'?[['smash','Smash · click'],['stomp','Stomp · Q'],['breath','Breath · E']]:[['tank','Tank · 35'],['turret','Turret · 50'],['repair','Repair · 30'],['missile','Missile · 60'],['freeze','Freeze · 40']];
 for(const [type,label]of items){const b=document.createElement('button');b.dataset.type=type;b.dataset.label=label;b.textContent=label;b.onclick=()=>{if(role==='kaiju')send({type});else{selected=type;for(const n of $('controls').children)n.classList.toggle('active',n===b);}};$('controls').append(b);if(type===selected)b.classList.add('active');}
 $('hint').textContent=role==='kaiju'?'WASD move · drag to look · click smash · Q stomp · E breath. VR: left stick move, right stick turn, trigger smash, grip stomp, A/X breath.':'Choose an order, then tap the map. Orange = kaiju · blue = units · green = intact buildings. Credits regenerate at 7/sec. Repair cannot rebuild rubble.';
 if(role==='kaiju')setup3D();else{$('map').hidden=false;$('map').onpointerdown=e=>{const rect=$('map').getBoundingClientRect(),scale=Math.min(rect.width,rect.height)/80;send({type:selected,x:(e.clientX-rect.left-rect.width/2)/scale,z:(e.clientY-rect.top-rect.height/2)/scale});};}
}
function updateUI(players){
 const lost=state.buildings.filter(b=>b.hp<=0).length;$('health').textContent=Math.ceil(state.kaiju.hp);$('damage').textContent=Math.round(lost/state.buildings.length*100)+'%';$('time').textContent=`${Math.floor(state.remaining/60)}:${String(Math.ceil(state.remaining%60)).padStart(2,'0')}`;$('credits').textContent=Math.floor(state.credits);
 $('status').textContent=state.phase==='ended'?`${state.winner.toUpperCase()} WINS — ${state.reason}`:paused?'PAUSED — waiting for disconnected player':state.phase==='lobby'?'Ready to level the playing field?':`${role==='kaiju'?'DESTROY THE CITY':'PROTECT THE CITY'}${state.slow>0?' · KAIJU FROZEN':''}`;
 $('joinInfo').textContent=`Kaiju ${players.kaiju?'●':'○'} / Defender ${players.defender?'●':state.bot?'AI':'○'} · Room ${$('room').value.toUpperCase()}`;
 $('start').hidden=state.phase!=='lobby';$('practice').hidden=state.phase!=='lobby'||role!=='kaiju';$('reset').hidden=state.phase!=='ended';
 for(const b of $('controls').children){const cd=state.cool[b.dataset.type]||0;b.textContent=b.dataset.label+(cd>0?` (${cd.toFixed(1)}s)`:'');b.disabled=state.phase!=='playing'||paused||cd>0;}
}
function drawMap(){const c=$('map'),r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#111e2b';ctx.fillRect(0,0,r.width,r.height);ctx.translate(r.width/2,r.height/2);const s=Math.min(r.width,r.height)/80;ctx.scale(s,s);ctx.lineWidth=.15;ctx.strokeStyle='#2d4253';for(let i=-36;i<=36;i+=8){ctx.beginPath();ctx.moveTo(i,-36);ctx.lineTo(i,36);ctx.stroke();ctx.beginPath();ctx.moveTo(-36,i);ctx.lineTo(36,i);ctx.stroke();}for(const b of state.buildings){ctx.fillStyle=b.hp<=0?'#39434a':b.hp<50?'#c28a52':'#5cbaad';ctx.fillRect(b.x-2.5,b.z-2.5,5,5);if(b.hp>0){ctx.fillStyle='#14242d';ctx.fillRect(b.x-2.5,b.z+1.6,5, .5);ctx.fillStyle='#c9fff0';ctx.fillRect(b.x-2.5,b.z+1.6,b.hp/20,.5);}}for(const u of state.units){ctx.fillStyle='#66b9ff';ctx.beginPath();ctx.arc(u.x,u.z,u.type==='tank'?1:1.5,0,Math.PI*2);ctx.fill();}for(const e of state.effects){ctx.strokeStyle=e.type==='repair'?'#70ffc0':e.type==='freeze'?'#87d9ff':'#ffb261';ctx.lineWidth=.5;ctx.beginPath();ctx.arc(e.x,e.z,e.r*(1-e.ttl/.9),0,7);ctx.stroke();}const k=state.kaiju;ctx.save();ctx.translate(k.x,k.z);ctx.rotate(-k.yaw);ctx.fillStyle='#ff7749';ctx.beginPath();ctx.moveTo(0,-3);ctx.lineTo(-2,2);ctx.lineTo(2,2);ctx.closePath();ctx.fill();ctx.restore();}
function box(w,h,d,color){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color}));}
function setup3D(){
 scene=new THREE.Scene();scene.background=new THREE.Color('#142332');scene.fog=new THREE.Fog('#142332',55,130);camera=new THREE.PerspectiveCamera(75,1,.1,180);rig=new THREE.Group();rig.add(camera);scene.add(rig);
 renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.xr.enabled=true;$('view').prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xc5eaff,0x31352b,2));const light=new THREE.DirectionalLight(0xffd0a0,2);light.position.set(-25,60,20);scene.add(light);
 const ground=box(90,.3,90,0x263c46);ground.position.y=-.2;scene.add(ground);for(let i=-36;i<=36;i+=8){const a=box(1,.05,80,0x152530);a.position.set(i,.02,0);scene.add(a);const b=box(80,.05,1,0x152530);b.position.set(0,.02,i);scene.add(b);}
 for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);rig.add(controller);controller.addEventListener('selectstart',()=>send({type:'smash'}));controller.addEventListener('squeezestart',()=>send({type:'stomp'}));const grip=renderer.xr.getControllerGrip(i);grip.add(box(.25,.22,.4,0xff7749));rig.add(grip);}
 vrButton=VRButton.createButton(renderer);document.querySelector('footer').append(vrButton);Object.assign(vrButton.style,{position:'static',transform:'none',marginTop:'8px',width:'auto'});renderer.xr.addEventListener('sessionend',()=>{pitch=0;});
 const canvas=renderer.domElement;let down,dragging=false;canvas.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};dragging=false;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)+Math.abs(dy)>2)dragging=true;yaw-=dx*.005;pitch=Math.max(-1.1,Math.min(.7,pitch-dy*.005));down={x:e.clientX,y:e.clientY};};canvas.onpointerup=()=>{if(!dragging)send({type:'smash'});down=null;};canvas.onpointercancel=()=>down=null;
 window.addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(!e.repeat&&e.code==='KeyQ')send({type:'stomp'});if(!e.repeat&&e.code==='KeyE')send({type:'breath'});});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{for(const k in keys)keys[k]=false;send({type:'move',x:0,z:0,yaw});});
 const hudCanvas=document.createElement('canvas');hudCanvas.width=1024;hudCanvas.height=256;const hudTexture=new THREE.CanvasTexture(hudCanvas);const hud=new THREE.Mesh(new THREE.PlaneGeometry(1.6,.4),new THREE.MeshBasicMaterial({map:hudTexture,transparent:true,depthTest:false}));hud.position.set(0,-.55,-2);hud.renderOrder=99;camera.add(hud);let hudTime=0;
 let last=0,sent=0,buttons=false;renderer.setAnimationLoop(now=>{const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!state)return;
  let mx=(keys.KeyD?1:0)-(keys.KeyA?1:0),mz=(keys.KeyS?1:0)-(keys.KeyW?1:0);const session=renderer.xr.getSession();let breath=false;if(session){for(const source of session.inputSources){const gp=source.gamepad;if(!gp)continue;const axes=gp.axes;if(source.handedness==='left'){mx=axes[2]??axes[0]??0;mz=axes[3]??axes[1]??0;}if(source.handedness==='right')yaw-=(axes[2]??axes[0]??0)*dt*1.5;breath ||=!!gp.buttons[4]?.pressed;}if(breath&&!buttons)send({type:'breath'});buttons=breath;}
  if(Math.abs(mx)<.15)mx=0;if(Math.abs(mz)<.15)mz=0;const x=mx*Math.cos(yaw)+mz*Math.sin(yaw),z=-mx*Math.sin(yaw)+mz*Math.cos(yaw);if(now-sent>50&&state.phase==='playing'&&!paused){send({type:'move',x,z,yaw});sent=now;}
  hud.visible=!!session;if(session&&now-hudTime>150){hudTime=now;const ctx=hudCanvas.getContext('2d');ctx.clearRect(0,0,1024,256);ctx.fillStyle='#0b1119dd';ctx.fillRect(0,0,1024,256);ctx.fillStyle='#ffffff';ctx.font='bold 34px sans-serif';ctx.fillText($('status').textContent.slice(0,48),25,50);ctx.font='30px sans-serif';ctx.fillText(`HP ${Math.ceil(state.kaiju.hp)}   City lost ${$('damage').textContent} / 60%   ${$('time').textContent}`,25,110);ctx.fillText(`Smash ${state.cool.smash.toFixed(1)}s   Stomp ${state.cool.stomp.toFixed(1)}s   Breath ${state.cool.breath.toFixed(1)}s`,25,170);ctx.font='24px sans-serif';ctx.fillText('Trigger: smash  |  Grip: stomp  |  A/X: breath',25,220);hudTexture.needsUpdate=true;}
  rig.position.set(state.kaiju.x,session?8:10,state.kaiju.z);rig.rotation.y=yaw;if(!session){camera.position.set(0,0,0);camera.rotation.set(pitch,0,0);}
  for(const b of state.buildings){let mesh=objects.get(b.id);if(!mesh){mesh=box(5,b.h,5,0x6caaa8);mesh.position.set(b.x,b.h/2,b.z);scene.add(mesh);objects.set(b.id,mesh);}const target=b.hp<=0?.04:1;mesh.scale.y+=(target-mesh.scale.y)*.2;mesh.position.y=b.h*mesh.scale.y/2;mesh.material.color.setHex(b.hp<=0?0x41444a:b.hp<50?0xbf8652:0x6caaa8);}
  for(const u of state.units){let mesh=unitObjects.get(u.id);if(!mesh){mesh=box(2,u.type==='tank'?1:3,2,0x60aaff);scene.add(mesh);unitObjects.set(u.id,mesh);}mesh.position.set(u.x,u.type==='tank'?.5:1.5,u.z);}for(const [id,mesh]of unitObjects)if(!state.units.some(u=>u.id===id)){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();unitObjects.delete(id);}
  for(const e of state.effects){let mesh=effectObjects.get(e.id);if(!mesh){mesh=new THREE.Mesh(new THREE.RingGeometry(.8,1,32),new THREE.MeshBasicMaterial({color:e.type==='freeze'?0x80dfff:e.type==='repair'?0x70ffc0:0xff8844,side:THREE.DoubleSide,transparent:true}));mesh.rotation.x=-Math.PI/2;scene.add(mesh);effectObjects.set(e.id,mesh);}mesh.position.set(e.x,.2,e.z);mesh.scale.setScalar(Math.max(.1,e.r*(1-e.ttl/.9)));mesh.material.opacity=Math.max(0,e.ttl);}for(const [id,mesh]of effectObjects)if(!state.effects.some(e=>e.id===id)){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();effectObjects.delete(id);}
  const rect=$('view').getBoundingClientRect();if(!session&&(renderer.domElement.width!==Math.round(rect.width*renderer.getPixelRatio())||renderer.domElement.height!==Math.round(rect.height*renderer.getPixelRatio()))){renderer.setSize(rect.width,rect.height);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();}renderer.render(scene,camera);
 });
}
window.addEventListener('resize',()=>{if(role==='defender'&&state)drawMap();});

